services:
  - type: web
    name: astra-backend
    env: python
    plan: free
    region: singapore
    rootDir: apps/api
    buildCommand: "./build.sh"
    startCommand: "python wait_for_db.py && python manage.py migrate && gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: astra-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: FORCE_SYNC
        value: "true"

databases:
  - name: astra-postgres
    databaseName: astra
    user: astra_user
    plan: free
    region: singapore
