services:
  - type: web
    name: astra-backend
    env: python
    plan: free
    region: singapore
    rootDir: apps/api
    buildCommand: "./build.sh"
    startCommand: "python wait_for_db.py && python manage.py migrate && python manage.py sync_events && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: ASTRA_DB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "api.astraietm.in,astraietm.in,www.astraietm.in,astra-backend-9dbv.onrender.com"
      - key: FORCE_SYNC
        value: "true"


